- .travis.gpg.sh
- .travis.settings.xml
- .travis.yml
- README.md
- pom.xml
See the Travis CI project here:  https://travis-ci.org/salesforce/mirus
https://github.com/salesforce/mirus/issues/3
> Add Travis CI build and deploy support

- src/main/java/com/salesforce/mirus/MirusSourceTask.java
Allow consumer shutdown logic to be accessible to
classes that inherit this class. Also pull logic out
into a separate class to decouple it from the poll() method.
> Isolate MirusSourceTask consumer shutdown logic

- pom.xml
According to `mvn versions:display-dependency-updates`, the following new versions for dependencies are found.
```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   com.fasterxml.jackson.dataformat:jackson-dataformat-csv ...
[INFO]                                                           2.9.4 -> 2.9.6
[INFO]   org.apache.kafka:connect-api .......................... 1.1.0 -> 2.0.0
[INFO]   org.apache.kafka:connect-json ......................... 1.1.0 -> 2.0.0
[INFO]   org.apache.kafka:connect-runtime ...................... 1.1.0 -> 2.0.0
[INFO]   org.mockito:mockito-core ............................ 2.8.47 -> 2.21.0
```
Undoubtedly, we should not upgrade kafka's major version without necessary preparations and verifications. Apart from that, it may be …
> Bump mockito-core to the latest version

- config/quickstart-worker.properties
- src/main/java/com/salesforce/mirus/ByteArrayConverter.java
We should now be using org.apache.kafka.connect.converters.ByteArrayConverter
See https://github.com/salesforce/mirus/issues/10
> Deprecate com.salesforce.mirus.ByteArrayConverter

- src/main/java/com/salesforce/mirus/HerderStatusMonitor.java
Tasks restarts should only happen on their assigned worker.
> Fix task restart logic

- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/offsets/MirusOffsetTool.java
- src/main/java/com/salesforce/mirus/offsets/OffsetFetcher.java
- src/test/java/com/salesforce/mirus/MirusSourceTaskTest.java
- src/test/java/com/salesforce/mirus/offsets/OffsetSerDeTest.java
* Handle tombstone records in offset tool
In order to support the ability to delete offset entries in the Mirus configured offset topic, the offset tool should be able to handle offset entries of null. Kafka will eventually delete records in a compact topic that has the same key value of a tombstone record. This deletion doesn't happen instantly and depends on different configuration settings.
An outcome of this feature of handling null offsets is the ability of a consumer application, such as an offset checker, to have offsets of partitions of a deleted topic marked with a tombstone record and therefore filtered out.
> Handle tombstone records in offset tool (#1)

- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/config/SourceConfigDefinition.java
- src/main/java/com/salesforce/mirus/config/TaskConfig.java
- src/main/java/com/salesforce/mirus/config/TaskConfigDefinition.java
- src/test/java/com/salesforce/mirus/MirusSourceTaskTest.java
- src/test/java/com/salesforce/mirus/config/TaskConfigTest.java
This allows the Task to be able to create SourceRecords which might be coming from an already generated Kafka Connect Record.
More context: https://github.com/salesforce/mirus/issues/25#issuecomment-444964030
> Support KafkaConnect Records via Converters

- pom.xml
- src/main/java/com/salesforce/mirus/Mirus.java
Upgrade and merge recent upstream changes from `ConnectDistributed`, including calling `rest.start` in `startConnect` as identified in issue #36.
> Update to Kafka Connect 2.2.0

- README.md
- pom.xml
- src/main/java/com/salesforce/mirus/KafkaMonitor.java
- src/main/java/com/salesforce/mirus/SourcePartitionValidator.java
- src/main/java/com/salesforce/mirus/config/SourceConfig.java
- src/main/java/com/salesforce/mirus/config/SourceConfigDefinition.java
- src/test/java/com/salesforce/mirus/KafkaMonitorTest.java
- src/test/java/com/salesforce/mirus/SourcePartitionValidatorTest.java
- src/test/java/com/salesforce/mirus/TaskConfigBuilderTest.java
- src/test/java/com/salesforce/mirus/config/SourceConfigTest.java
Add support for RegexRouter transforms and topic name prefixes and
suffixes when checking the destination cluster for topic name.
Previously the KafkaMonitor only checked for the original topic name,
even if messages would be replicated to a different topic.
Prefixes and suffixes are applied first, since transforms are only
applied to records after being returned from the MirusSourceTask::poll
method.
Other routers aren't currently supported. The Kafka Connect
TimestampRouter routes based of information within each message, so
the required topic name can't be determined ahead of time. The
KafkaMonitor assumes any transform that contains the phrase "Router"
would rename topics and logs a warning about mirroring when identified.
> Handle topic renaming when checking destination partitions

- src/main/java/com/salesforce/mirus/KafkaMonitor.java
To correctly start at the first backoff wait of 0 seconds we need to
start at index 0, which is one less than the number of consecutive
errors. Wrap in a min/max check to ensure we stay within the bounds of
the BACKOFF_WAIT_SECONDS array.
> Use zero index for KafkaMonitorBackoff

- .travis.yml
This is required because `oraclejdk8` is not longer available. We should upgrade to `openjdk11` soon.
> Use openjdk8 in Travis CI

- pom.xml
- src/main/java/com/salesforce/mirus/Mirus.java
- src/test/java/com/salesforce/mirus/MirusSourceTaskTest.java
- Upgrade library
- It's not possible to create records with `null` headers, thus we create an empty headers list with `new RecordHeaders()`
- Seems like it's not necessary to start the herder manually anymore, check https://github.com/apache/kafka/blob/2.3.0/connect/runtime/src/main/java/org/apache/kafka/connect/cli/ConnectDistributed.java#L99
- The renaming configs were kept and also the monitoring thread
- It's hard to test this since it requires some manual testing, please double check the work!
P.s.: Would you please make a new release after this?
> Upgrade to Kafka 2.3.1

- src/main/java/com/salesforce/mirus/Mirus.java
- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/config/TaskConfig.java
- src/main/java/com/salesforce/mirus/config/TaskConfigDefinition.java
- src/test/java/com/salesforce/mirus/MirusSourceTaskTest.java
This works around the KIP-320 bug (in Kafka <2.3.0), where the current consumer offset can become invalid after partition leadership changes, causing the consumer to reset to the start of the partition and duplicate records to be consumed. In this change we filter out duplicates before they reach the producer. 
Note that this change does not need to be applied to master as it uses Kafka 2.3.1.
> Skip records that have already been consumed by a task

- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/config/TaskConfig.java
- src/main/java/com/salesforce/mirus/config/TaskConfigDefinition.java
- src/test/java/com/salesforce/mirus/MirusSourceTaskTest.java
Back-port changes related to handling data replays in brach 0.2.x into the main branch. Make default behaviour of handling duplicates is IGNORE.
> Backport handling data replay

- README.md
- pom.xml
- src/main/java/com/salesforce/mirus/KafkaMonitor.java
- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/config/SourceConfig.java
- src/main/java/com/salesforce/mirus/config/SourceConfigDefinition.java
- src/main/java/com/salesforce/mirus/config/TaskConfigDefinition.java
- src/test/java/com/salesforce/mirus/KafkaMonitorTest.java
- src/test/java/com/salesforce/mirus/config/SourceConfigTest.java
The main change here is treating the configs with prefix `destination.` as an override to the `consumer.` configs. This means that the connection to the _destination_ cluster's configs will be the combination of the default consumer configs with any override set using the prefix `destination.`.
> Provide ability to override kafka-monitor destination configs

- pom.xml
- src/main/java/com/salesforce/mirus/Mirus.java
- src/test/java/com/salesforce/mirus/offsets/OffsetSetterTest.java
* Updates Mirus to 2.6.1
* Adds additional test to OffsetSetterTest for testing more cases.
* Adds schema configuration to JsonConverter in OffsetSetterTest due to changes in 2.4.0
* Adds comments to suppress Javadoc warnings
> Upgrade Mirus to Kafka Connect 2.6.1

- pom.xml
The current method of using application keys is an additional step to upload
using ssh keys avoids the need to generate application keys.
> Switch to using ssh based authentication to GitHub

- README.md
- src/main/java/com/salesforce/mirus/MirusSourceTask.java
- src/main/java/com/salesforce/mirus/metrics/AbstractMirusJmxReporter.java
- src/main/java/com/salesforce/mirus/metrics/MirrorJmxReporter.java
* Adds latency reporting on a per-topic basis to Mirus
* Makes all JMX Reporters AutoClosable
> Add Latency Reporting to Mirus

- src/main/java/com/salesforce/mirus/MirusSourceTask.java
The current latency is incorrect when the destination cluster is using `log.message.timestamp.type=LogAppendTime`. In this case the metadata timestamp will be initialized when the record is written to the target broker, so we don't see overall end-to-end latency.
> Use sourceRecord timestamp as reference for end-to-end latency

- .github/workflows/ci.yml
- pom.xml
- src/main/java/com/salesforce/mirus/metrics/MirrorJmxReporter.java
- src/test/java/com/salesforce/mirus/metrics/MirrorJmxReporterTest.java
Changes:
- upgrade codebase to Java 11
- Switch to SpotBugs as FindBugs doesn't work from Java 9+
- Add histogram latency metrics
> Add simple latency histogram metrics
